# Generated by Django 3.0.3 on 2020-02-27 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('g_grade_id', models.AutoField(primary_key=True, serialize=False, verbose_name='grade id')),
                ('g_grade_name', models.CharField(max_length=50, unique=True, verbose_name='grade name')),
                ('g_grade_isactive', models.BooleanField(default=True, verbose_name='is grade active')),
                ('g_grade_created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='grade created on')),
                ('g_grade_updated_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='grade updated on')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'tblGrade',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('qt_questiontype_id', models.AutoField(primary_key=True, serialize=False, verbose_name='questiontype id')),
                ('qt_questiontype_name', models.CharField(max_length=100, unique=True, verbose_name='questiontype name')),
                ('qt_questiontype_isactive', models.BooleanField(default=True, verbose_name='is questiontype active')),
            ],
            options={
                'verbose_name': 'QuestionType',
                'verbose_name_plural': 'QuestionTypes',
                'db_table': 'lkpQuestionType',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('s_subject_id', models.AutoField(primary_key=True, serialize=False, verbose_name='subject id')),
                ('s_subject_name', models.CharField(max_length=50, unique=True, verbose_name='subject name')),
                ('s_subject_desc', models.TextField(blank=True, null=True, verbose_name='subject description')),
                ('s_subject_image', models.ImageField(blank=True, default='background.png', upload_to='', verbose_name='subject image')),
                ('s_subject_isactive', models.BooleanField(default=True, verbose_name='is subject active')),
                ('s_subject_created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='subject created on')),
                ('s_subject_updated_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='subject updated on')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'tblSubject',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('t_topic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='topic id')),
                ('t_topic_name', models.CharField(max_length=50, unique=True, verbose_name='topic name')),
                ('t_topic_desc', models.TextField(blank=True, null=True, verbose_name='topic description')),
                ('t_topic_isactive', models.BooleanField(default=True, verbose_name='is topic active')),
                ('t_topic_subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Subject', verbose_name='topic subject id')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'tblTopic',
                'unique_together': {('t_topic_name', 't_topic_subject_id')},
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('st_subtopic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='subtopic id')),
                ('st_subtopic_name', models.CharField(max_length=50, unique=True, verbose_name='subtopic name')),
                ('st_subtopic_desc', models.TextField(blank=True, null=True, verbose_name='subtopic description')),
                ('st_subtopic_isactive', models.BooleanField(default=True, verbose_name='is subtopic active')),
                ('st_subtopic_grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Grade', verbose_name='topic grade id')),
                ('st_subtopic_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Topic', verbose_name='subtopic topic id')),
            ],
            options={
                'verbose_name': 'SubTopic',
                'verbose_name_plural': 'SubTopics',
                'db_table': 'tblSubTopic',
                'unique_together': {('st_subtopic_name', 'st_subtopic_grade_id')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('q_quiz_id', models.AutoField(primary_key=True, serialize=False, verbose_name='quiz id')),
                ('q_quiz_name', models.CharField(max_length=100, unique=True, verbose_name='quiz name')),
                ('q_quiz_isactive', models.BooleanField(default=True, verbose_name='is quiz active')),
                ('q_quiz_subtopic_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.SubTopic', verbose_name='quiz subtopic')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'tblQuiz',
                'unique_together': {('q_quiz_subtopic_id', 'q_quiz_name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_question_id', models.AutoField(primary_key=True, serialize=False, verbose_name='question id')),
                ('q_question_text', models.CharField(max_length=250, unique=True, verbose_name='question text')),
                ('qt_question_isactive', models.BooleanField(default=True, verbose_name='is question active')),
                ('q_question_questiontype_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.QuestionType', verbose_name='question type')),
                ('q_question_quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.Quiz', verbose_name='question quiz id')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'tblQuestion',
                'unique_together': {('q_question_questiontype_id', 'q_question_quiz_id', 'q_question_text')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('a_answer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='answer id')),
                ('a_answer_text', models.CharField(max_length=250, verbose_name='answer text')),
                ('a_answer_iscorrect', models.BooleanField(default=False, verbose_name='is correct answer')),
                ('a_answer_isactive', models.BooleanField(default=True, verbose_name='is answer active')),
                ('a_answer_question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.Question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'tblAnswer',
                'unique_together': {('a_answer_question_id', 'a_answer_text')},
            },
        ),
    ]
