# Generated by Django 3.0.3 on 2020-02-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('st_subtopic_name', 'st_subtopic_grade_id', 'st_subtopic_topic_id')},
        ),
    ]
