# Generated by Django 3.0.3 on 2020-02-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200227_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='st_subtopic_name',
            field=models.CharField(max_length=50, verbose_name='subtopic name'),
        ),
    ]
