# Generated by Django 3.0.3 on 2020-03-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20200227_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_question_hint',
            field=models.TextField(default='Hint is Not Provided', max_length=250, verbose_name='question hint'),
        ),
    ]
