# Generated by Django 3.0.3 on 2020-03-11 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_question_q_question_hint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qt_question_isactive',
            new_name='q_question_isactive',
        ),
    ]
