# Generated by Django 3.0.3 on 2020-02-24 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200211_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_account_created',
            field=models.DateField(default=datetime.date.today, verbose_name='student account creted on'),
        ),
        migrations.AddField(
            model_name='student',
            name='s_account_updated_on',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='student account updated on'),
        ),
    ]
