# Generated by Django 3.0.3 on 2020-02-26 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200224_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_account_updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='student account updated on'),
        ),
    ]
