# Generated by Django 3.0.3 on 2020-03-24 23:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20200310_2300'),
        ('accounts', '0004_auto_20200226_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_account_created',
            field=models.DateField(default=datetime.date.today, verbose_name='student account created on'),
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('sr_studentresponse_id', models.AutoField(primary_key=True, serialize=False, verbose_name='student response id')),
                ('sr_studentresponse_score', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='student answer score')),
                ('sr_studentresponse_created_on', models.DateField(default=datetime.date.today, verbose_name='student response created on')),
                ('sr_studentresponse_answer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.Answer', verbose_name='given answer')),
                ('sr_studentresponse_student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Student Response',
                'verbose_name_plural': 'Student Responses',
                'db_table': 'tblStudentResponse',
            },
        ),
    ]
