# Generated by Django 2.2.6 on 2020-03-27 21:11

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20200310_2300'),
        ('accounts', '0005_auto_20200324_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresponse',
            name='sr_studentresponse_answer_id',
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='sr_studentresponse_que_ans',
            field=jsonfield.fields.JSONField(max_length=1000, null=True, verbose_name='Student Response Question And Answer'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='sr_studentresponse_quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='activity.Quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='sr_studentresponse_created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='student response created on'),
        ),
    ]
