# Generated by Django 2.2.6 on 2020-03-30 00:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200327_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='sr_studentresponse_que_ans',
            field=jsonfield.fields.JSONField(max_length=10000, null=True, verbose_name='Student Response Question And Answer'),
        ),
    ]
